login: &login
  access_key_id: <%= ENV['S3_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET'] %>

development:
  bucket_name: portlandproductions_development
  <<: *login
  distribution_domain: s3.amazonaws.com/portlandproductions_development

test:
  bucket_name: portlandproductions_test
  <<: *login
  distribution_domain: s3.amazonaws.com/portlandproductions_test

production:
  bucket_name: portlandproductions_production
  <<: *login
  distribution_domain: s3.amazonaws.com/portlandproductions_production
