login: &login
  access_key_id: <%= ENV['AMAZON_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AMAZON_SECRET_ACCESS_KEY'] %>

development:
  bucket_name: portlandproductions_development
  <<: *login
  distribution_domain: s3.amazonaws.com/portlandproductions_development

test:
  bucket_name: portlandproductions_test
  <<: *login
  distribution_domain: s3.amazonaws.com/portlandproductions_test

production:
  bucket_name: portlandproductions_production
  <<: *login
  distribution_domain: s3.amazonaws.com/portlandproductions_production
